### ISSUE TITLE
OT: cssman on GitHub?

### ISSUE THREAD

**Issue by dandv** [maximilianschmitt/iniquest#1]
Hi Max,

I found your [cssman pacakge](https://www.npmjs.com/package/cssman) via [this SO question](http://stackoverflow.com/questions/4588119/get-elements-css-selector-without-element-id#comment50195492_29318219). Since commenting on the [gist](https://gist.github.com/asfaltboy/8aea7435b888164e8563) by @asfaltboy [doesn't notify people](https://github.com/isaacs/github/issues/21), I'm creating this issue.

The npm package doesn't have a GitHub field, and I couldn't find the source repo (if there is one). In the meantime [the Chromium code](https://chromium.googlesource.com/chromium/blink/+/master/Source/devtools/front_end/components/DOMPresentationUtils.js) has changed a bit vs. the gist, and I was wondering if you wanted to push an update.

The background is that I'm looking for a [CSS selector generator library](https://github.com/fczbkk/css-selector-generator-benchmark/issues/1) that's robust to changes in the page structure.

**Comment by maximilianschmitt** [comment]
Hi Dan, thanks for contacting me. Yeah, I totally missed the comments on the gist, sorry about that. I published the module on GitHub, pull requests would be great if you would like to update the module: https://github.com/maximilianschmitt/cssman

Thanks!
